# Generated by Django 5.2.16 on 2026-07-16 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bluemap_configs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('min_x', models.IntegerField()),
                ('min_z', models.IntegerField()),
                ('max_x', models.IntegerField()),
                ('max_z', models.IntegerField()),
                ('min_y', models.IntegerField(blank=True, null=True)),
                ('max_y', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorldFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=160)),
                ('source_path', models.CharField(max_length=1024, unique=True)),
                ('detected_dimensions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('owner_team', models.CharField(blank=True, max_length=160)),
                ('output_path', models.CharField(blank=True, max_length=1024)),
                ('default_bluemap_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_projects', to='bluemap_configs.bluemapprofile')),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('assign_project_users', 'Can assign users to project roles'), ('manage_project_visible_worlds', 'Can manage visible world folders')],
            },
        ),
        migrations.CreateModel(
            name='Atlas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atlases', to='projects.project')),
                ('world_folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atlases', to='projects.worldfolder')),
            ],
            options={
                'ordering': ['project__name', 'display_name'],
                'permissions': [('manage_atlas', 'Can manage atlas')],
                'unique_together': {('project', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProjectVisibleWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('made_visible_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visible_world_assignments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('world_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.worldfolder')),
            ],
            options={
                'ordering': ['project__name', 'world_folder__display_name'],
                'unique_together': {('project', 'world_folder')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='visible_worlds',
            field=models.ManyToManyField(blank=True, related_name='visible_in_projects', through='projects.ProjectVisibleWorld', to='projects.worldfolder'),
        ),
        migrations.CreateModel(
            name='Render',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bluemap_map_id', models.SlugField(max_length=180)),
                ('display_name', models.CharField(max_length=160)),
                ('dimension', models.CharField(choices=[('minecraft:overworld', 'Overworld'), ('minecraft:the_nether', 'The Nether'), ('minecraft:the_end', 'The End'), ('custom', 'Custom')], max_length=80)),
                ('custom_dimension', models.CharField(blank=True, max_length=160)),
                ('sorting', models.IntegerField(default=0)),
                ('perspective_preset', models.CharField(choices=[('day', 'Day'), ('night', 'Night'), ('cave', 'Cave'), ('flat', 'Flat'), ('custom', 'Custom')], default='day', max_length=20)),
                ('start_position', models.JSONField(blank=True, default=dict)),
                ('lighting_options', models.JSONField(blank=True, default=dict)),
                ('cave_options', models.JSONField(blank=True, default=dict)),
                ('storage_profile', models.CharField(blank=True, max_length=160)),
                ('output_path', models.CharField(blank=True, max_length=1024)),
                ('is_enabled', models.BooleanField(default=True)),
                ('atlas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renders', to='projects.atlas')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.region')),
            ],
            options={
                'ordering': ['atlas__project__name', 'atlas__display_name', 'sorting', 'display_name'],
                'permissions': [('manage_render', 'Can manage render'), ('trigger_render', 'Can trigger render')],
                'unique_together': {('atlas', 'bluemap_map_id')},
            },
        ),
    ]
