# Generated by Django 5.2.16 on 2026-07-16 21:48

import uuid

import projects.models
from django.db import migrations, models


def make_existing_bluemap_ids_unique(apps, schema_editor):
    Render = apps.get_model("projects", "Render")
    seen = set()

    for render in Render.objects.order_by("id"):
        if render.bluemap_map_id and render.bluemap_map_id not in seen:
            seen.add(render.bluemap_map_id)
            continue

        new_map_id = f"render-{uuid.uuid4()}"
        while new_map_id in seen:
            new_map_id = f"render-{uuid.uuid4()}"

        render.bluemap_map_id = new_map_id
        render.save(update_fields=["bluemap_map_id"])
        seen.add(new_map_id)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(make_existing_bluemap_ids_unique, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='render',
            name='bluemap_map_id',
            field=models.SlugField(default=projects.models.generate_bluemap_map_id, editable=False, max_length=180, unique=True),
        ),
    ]
