# Generated by Django 5.2.16 on 2026-07-16 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_render_bluemap_map_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='render',
            unique_together=set(),
        ),
    ]
