# Generated by Django 5.2.16 on 2026-07-17 19:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_render_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='render',
            name='ambient_light',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='render',
            name='cave_detection_ocean_floor',
            field=models.IntegerField(default=-5),
        ),
        migrations.AddField(
            model_name='render',
            name='cave_detection_uses_block_light',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='render',
            name='edge_light_strength',
            field=models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AddField(
            model_name='render',
            name='enable_flat_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='render',
            name='enable_free_flight_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='render',
            name='enable_hires',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='render',
            name='enable_perspective_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='render',
            name='ignore_missing_light_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='render',
            name='min_inhabited_time',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='render',
            name='remove_caves_below_y',
            field=models.IntegerField(default=55),
        ),
        migrations.AddField(
            model_name='render',
            name='render_edges',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='render',
            name='sky_color',
            field=models.CharField(default='#7dabff', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex color like #7dabff.', regex='^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AddField(
            model_name='render',
            name='sky_light',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='render',
            name='void_color',
            field=models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex color like #7dabff.', regex='^#[0-9a-fA-F]{6}$')]),
        ),
    ]
