# Generated by Django 5.2.16 on 2026-07-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='render',
            name='marker_sets',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='render',
            name='render_mask',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
