# Generated by Django 5.2.16 on 2026-07-19 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_render_marker_sets_render_render_mask'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinecraftResourceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=160)),
                ('root_path', models.CharField(max_length=1024, unique=True)),
                ('mods_path', models.CharField(blank=True, max_length=1024)),
                ('minecraft_version', models.CharField(blank=True, max_length=40)),
                ('mod_loader', models.CharField(choices=[('forge', 'Forge'), ('neoforge', 'NeoForge'), ('fabric', 'Fabric'), ('quilt', 'Quilt'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('source_type', models.CharField(choices=[('server', 'Server'), ('modpack', 'Modpack or client instance'), ('custom', 'Custom path')], default='custom', max_length=20)),
                ('load_mod_resources_by_default', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_detected', models.BooleanField(default=False)),
                ('auto_detect', models.BooleanField(default=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.AddField(
            model_name='render',
            name='custom_mods_path',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='render',
            name='minecraft_version_override',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='render',
            name='resource_mode',
            field=models.CharField(choices=[('inherit', 'Use world or server default'), ('disabled', 'Vanilla resources only'), ('source', 'Choose a resource source'), ('custom', 'Use a custom mods path')], default='inherit', max_length=20),
        ),
        migrations.AddField(
            model_name='render',
            name='resource_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renders', to='projects.minecraftresourcesource'),
        ),
        migrations.AddField(
            model_name='worldfolder',
            name='default_resource_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worlds', to='projects.minecraftresourcesource'),
        ),
        migrations.CreateModel(
            name='MinecraftServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=160)),
                ('root_path', models.CharField(max_length=1024, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('resource_source', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minecraft_server', to='projects.minecraftresourcesource')),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.AddField(
            model_name='worldfolder',
            name='minecraft_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worlds', to='projects.minecraftserver'),
        ),
    ]
