# Generated by Django 5.2 on 2026-08-08

import projects.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_minecraftresourcesource_render_custom_mods_path_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="render",
            old_name="marker_sets",
            new_name="legacy_marker_sets_hocon",
        ),
        migrations.AlterField(
            model_name="render",
            name="legacy_marker_sets_hocon",
            field=models.TextField(blank=True, default="{}", editable=False),
        ),
        migrations.CreateModel(
            name="MarkerSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bluemap_id", models.SlugField(default=projects.models.generate_marker_set_id, editable=False, max_length=180)),
                ("label", models.CharField(max_length=160)),
                ("toggleable", models.BooleanField(default=True)),
                ("default_hidden", models.BooleanField(default=False)),
                ("sorting", models.IntegerField(default=0)),
                ("render", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="marker_sets", to="projects.render")),
            ],
            options={
                "ordering": ["sorting", "label", "id"],
            },
        ),
        migrations.CreateModel(
            name="Marker",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bluemap_id", models.SlugField(default=projects.models.generate_marker_id, editable=False, max_length=180)),
                ("marker_type", models.CharField(choices=[("poi", "Point of interest")], default="poi", max_length=20)),
                ("label", models.CharField(max_length=160)),
                ("detail", models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(4000)])),
                ("position_x", models.DecimalField(decimal_places=3, max_digits=14)),
                ("position_y", models.DecimalField(decimal_places=3, max_digits=14)),
                ("position_z", models.DecimalField(decimal_places=3, max_digits=14)),
                ("sorting", models.IntegerField(default=0)),
                ("listed", models.BooleanField(default=True)),
                ("min_distance", models.PositiveIntegerField(blank=True, null=True)),
                ("max_distance", models.PositiveIntegerField(blank=True, null=True)),
                ("icon", models.CharField(default="assets/poi.svg", editable=False, max_length=255)),
                ("anchor_x", models.IntegerField(default=25, editable=False)),
                ("anchor_y", models.IntegerField(default=45, editable=False)),
                ("marker_set", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="markers", to="projects.markerset")),
            ],
            options={
                "ordering": ["sorting", "label", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="markerset",
            constraint=models.UniqueConstraint(fields=("render", "bluemap_id"), name="unique_marker_set_bluemap_id_per_render"),
        ),
        migrations.AddConstraint(
            model_name="marker",
            constraint=models.UniqueConstraint(fields=("marker_set", "bluemap_id"), name="unique_marker_bluemap_id_per_set"),
        ),
    ]
