# Generated by Django 5.2 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_marker_marker_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="render",
            name="published_marker_snapshot",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="render",
            name="markers_published_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
