from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path

from accounts.views import (
    panel_settings,
    panel_users,
    panel_user_create,
    panel_user_edit,
    panel_user_project_access_add,
    panel_user_project_access_remove,
    profile_settings,
)
from assets.views import protected_render_asset
from projects.views import (
    add_project_user,
    archived_atlases,
    archived_renders,
    atlas_detail,
    create_atlas,
    create_project,
    create_render,
    create_resource_source,
    create_world_folder,
    archive_atlas,
    archive_project,
    archive_render,
    archive_world_folder,
    dashboard,
    edit_atlas,
    edit_project,
    edit_render,
    edit_resource_source,
    edit_world_folder,
    manage_projects,
    project_detail,
    project_members,
    project_worlds,
    remove_project_membership,
    restore_atlas,
    restore_render,
    restore_world_folder,
    scan_world_folders,
    world_folders,
)
from viewer.views import (
    cancel_render_job,
    render_config_preview,
    render_job_detail,
    render_status,
    render_viewer,
    trigger_render,
)

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', profile_settings, name='profile_settings'),
    path('settings/', panel_settings, name='panel_settings'),
    path('settings/projects/', manage_projects, name='manage_projects'),
    path('settings/projects/create/', create_project, name='create_project'),
    path('settings/projects/<int:project_id>/edit/', edit_project, name='edit_project'),
    path('settings/projects/<int:project_id>/archive/', archive_project, name='archive_project'),
    path('settings/world-folders/', world_folders, name='world_folders'),
    path('settings/world-folders/scan/', scan_world_folders, name='scan_world_folders'),
    path('settings/world-folders/create/', create_world_folder, name='create_world_folder'),
    path(
        'settings/resource-sources/create/',
        create_resource_source,
        name='create_resource_source',
    ),
    path(
        'settings/resource-sources/<int:source_id>/edit/',
        edit_resource_source,
        name='edit_resource_source',
    ),
    path('settings/world-folders/<int:world_id>/edit/', edit_world_folder, name='edit_world_folder'),
    path('settings/world-folders/<int:world_id>/archive/', archive_world_folder, name='archive_world_folder'),
    path('settings/world-folders/<int:world_id>/restore/', restore_world_folder, name='restore_world_folder'),
    path('settings/users/', panel_users, name='panel_users'),
    path('settings/users/create/', panel_user_create, name='panel_user_create'),
    path('settings/users/<int:user_id>/edit/', panel_user_edit, name='panel_user_edit'),
    path(
        'settings/users/<int:user_id>/project-access/add/',
        panel_user_project_access_add,
        name='panel_user_project_access_add',
    ),
    path(
        'settings/users/<int:user_id>/project-access/<int:membership_id>/remove/',
        panel_user_project_access_remove,
        name='panel_user_project_access_remove',
    ),
    path('projects/<slug:slug>/', project_detail, name='project_detail'),
    path('projects/<slug:slug>/members/', project_members, name='project_members'),
    path('projects/<slug:slug>/worlds/', project_worlds, name='project_worlds'),
    path('projects/<slug:slug>/atlases/archived/', archived_atlases, name='archived_atlases'),
    path('projects/<slug:slug>/atlases/create/', create_atlas, name='create_atlas'),
    path('projects/<slug:slug>/users/add/', add_project_user, name='add_project_user'),
    path(
        'projects/<slug:slug>/memberships/<int:membership_id>/remove/',
        remove_project_membership,
        name='remove_project_membership',
    ),
    path('atlases/<int:atlas_id>/edit/', edit_atlas, name='edit_atlas'),
    path('atlases/<int:atlas_id>/', atlas_detail, name='atlas_detail'),
    path('atlases/<int:atlas_id>/archive/', archive_atlas, name='archive_atlas'),
    path('atlases/<int:atlas_id>/restore/', restore_atlas, name='restore_atlas'),
    path('atlases/<int:atlas_id>/renders/archived/', archived_renders, name='archived_renders'),
    path('atlases/<int:atlas_id>/renders/create/', create_render, name='create_render'),
    path('renders/<int:render_id>/edit/', edit_render, name='edit_render'),
    path('renders/<int:render_id>/archive/', archive_render, name='archive_render'),
    path('renders/<int:render_id>/restore/', restore_render, name='restore_render'),
    path('renders/<int:render_id>/', render_viewer, name='render_viewer'),
    path('renders/<int:render_id>/config-preview/', render_config_preview, name='render_config_preview'),
    path('renders/<int:render_id>/status/', render_status, name='render_status'),
    path('renders/<int:render_id>/trigger/', trigger_render, name='trigger_render'),
    path('jobs/<int:job_id>/', render_job_detail, name='render_job_detail'),
    path('jobs/<int:job_id>/cancel/', cancel_render_job, name='cancel_render_job'),
    path(
        'renders/<int:render_id>/assets/<path:asset_path>',
        protected_render_asset,
        name='protected_render_asset',
    ),
]
