# Generated by Django 5.2.16 on 2026-07-16 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlueMapProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('config_template', models.TextField(default='maps: {\n  "{map_id}": {\n    world: "{world_path}"\n    dimension: "{dimension}"\n    name: "{display_name}"\n  }\n}\n')),
                ('command_template', models.CharField(default='{bluemap_cli} render --map "{map_id}"', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_content', models.TextField(blank=True)),
                ('new_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedConfigFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024)),
                ('content_hash', models.CharField(blank=True, max_length=128)),
                ('last_written_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='BlueMapRenderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advanced_fields', models.JSONField(blank=True, default=dict)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('adopted_manual_file', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='render_configs', to='bluemap_configs.bluemapprofile')),
            ],
            options={
                'ordering': ['render__atlas__project__name', 'render__display_name'],
            },
        ),
    ]
