# Generated by Django 5.2.16 on 2026-07-16 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bluemap_configs', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bluemaprenderconfig',
            name='render',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='projects.render'),
        ),
        migrations.AddField(
            model_name='configrevision',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configrevision',
            name='render_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='bluemap_configs.bluemaprenderconfig'),
        ),
        migrations.AddField(
            model_name='generatedconfigfile',
            name='render_config',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_file', to='bluemap_configs.bluemaprenderconfig'),
        ),
    ]
