# Generated by Django 5.2.16 on 2026-07-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluemap_configs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluemapprofile',
            name='config_template',
            field=models.TextField(default='maps: {{\n  "{map_id}": {{\n    world: "{world_path}"\n    dimension: "{dimension}"\n    name: "{display_name}"\n  }}\n}}\n'),
        ),
    ]
