# Generated by Django 5.2.16 on 2026-07-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluemap_configs', '0003_alter_bluemapprofile_config_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluemapprofile',
            name='command_template',
            field=models.CharField(default='{bluemap_cli} render --config "{config_dir}" --map "{map_id}"', max_length=500),
        ),
    ]
