# Generated by Django 5.2.16 on 2026-07-16 15:20

from django.db import migrations, models


OLD_DEFAULT = '{bluemap_cli} render --config "{config_dir}" --map "{map_id}"'
NEW_DEFAULT = '{bluemap_cli} -c "{config_dir}" -r'


def update_old_default_command_templates(apps, schema_editor):
    BlueMapProfile = apps.get_model('bluemap_configs', 'BlueMapProfile')
    BlueMapProfile.objects.filter(command_template=OLD_DEFAULT).update(
        command_template=NEW_DEFAULT
    )


class Migration(migrations.Migration):

    dependencies = [
        ('bluemap_configs', '0004_alter_bluemapprofile_command_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluemapprofile',
            name='command_template',
            field=models.CharField(default=NEW_DEFAULT, max_length=500),
        ),
        migrations.RunPython(
            update_old_default_command_templates,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
