# Generated by Django 5.2.16 on 2026-07-16 17:36

from django.db import migrations, models


OLD_DEFAULTS = [
    'maps: {\n  "{map_id}": {\n    world: "{world_path}"\n    dimension: "{dimension}"\n    name: "{display_name}"\n  }\n}\n',
    'maps: {{\n  "{map_id}": {{\n    world: "{world_path}"\n    dimension: "{dimension}"\n    name: "{display_name}"\n  }}\n}}\n',
]
NEW_DEFAULT = 'world: "{world_path}"\ndimension: "{dimension}"\nname: "{display_name}"\nsorting: {sorting}\nstart-pos: {{ x: 0, z: 0 }}\nsky-color: "#7dabff"\nvoid-color: "#000000"\nsky-light: 1\nambient-light: 0\nremove-caves-below-y: 55\ncave-detection-ocean-floor: -5\ncave-detection-uses-block-light: false\nmin-inhabited-time: 0\nrender-mask: []\nrender-edges: true\nedge-light-strength: 8\nenable-perspective-view: true\nenable-flat-view: true\nenable-free-flight-view: true\nenable-hires: true\nstorage: "{storage}"\nignore-missing-light-data: false\nmarker-sets: {{}}\n'


def update_legacy_config_templates(apps, schema_editor):
    BlueMapProfile = apps.get_model("bluemap_configs", "BlueMapProfile")
    BlueMapProfile.objects.filter(config_template__in=OLD_DEFAULTS).update(
        config_template=NEW_DEFAULT
    )


class Migration(migrations.Migration):

    dependencies = [
        ('bluemap_configs', '0007_update_legacy_render_command_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluemapprofile',
            name='config_template',
            field=models.TextField(default=NEW_DEFAULT),
        ),
        migrations.RunPython(
            update_legacy_config_templates,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
