# Generated by Django 5.2.16 on 2026-07-17 19:50

from django.db import migrations, models


REPLACEMENTS = [
    ('sky-color: "#7dabff"', 'sky-color: "{sky_color}"'),
    ('void-color: "#000000"', 'void-color: "{void_color}"'),
    ("sky-light: 1", "sky-light: {sky_light}"),
    ("ambient-light: 0", "ambient-light: {ambient_light}"),
    ("remove-caves-below-y: 55", "remove-caves-below-y: {remove_caves_below_y}"),
    ("cave-detection-ocean-floor: -5", "cave-detection-ocean-floor: {cave_detection_ocean_floor}"),
    ("cave-detection-uses-block-light: false", "cave-detection-uses-block-light: {cave_detection_uses_block_light}"),
    ("min-inhabited-time: 0", "min-inhabited-time: {min_inhabited_time}"),
    ("render-edges: true", "render-edges: {render_edges}"),
    ("edge-light-strength: 8", "edge-light-strength: {edge_light_strength}"),
    ("enable-perspective-view: true", "enable-perspective-view: {enable_perspective_view}"),
    ("enable-flat-view: true", "enable-flat-view: {enable_flat_view}"),
    ("enable-free-flight-view: true", "enable-free-flight-view: {enable_free_flight_view}"),
    ("enable-hires: true", "enable-hires: {enable_hires}"),
    ("ignore-missing-light-data: false", "ignore-missing-light-data: {ignore_missing_light_data}"),
]


def update_existing_map_templates(apps, schema_editor):
    BlueMapProfile = apps.get_model("bluemap_configs", "BlueMapProfile")
    for profile in BlueMapProfile.objects.all():
        updated_template = profile.config_template
        for old, new in REPLACEMENTS:
            updated_template = updated_template.replace(old, new)
        if updated_template != profile.config_template:
            profile.config_template = updated_template
            profile.save(update_fields=["config_template"])


class Migration(migrations.Migration):

    dependencies = [
        ('bluemap_configs', '0009_normalize_wrapped_map_config_templates'),
        ('projects', '0004_render_ambient_light_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluemapprofile',
            name='config_template',
            field=models.TextField(default='world: "{world_path}"\ndimension: "{dimension}"\nname: "{display_name}"\nsorting: {sorting}\nstart-pos: {{ x: 0, z: 0 }}\nsky-color: "{sky_color}"\nvoid-color: "{void_color}"\nsky-light: {sky_light}\nambient-light: {ambient_light}\nremove-caves-below-y: {remove_caves_below_y}\ncave-detection-ocean-floor: {cave_detection_ocean_floor}\ncave-detection-uses-block-light: {cave_detection_uses_block_light}\nmin-inhabited-time: {min_inhabited_time}\nrender-mask: []\nrender-edges: {render_edges}\nedge-light-strength: {edge_light_strength}\nenable-perspective-view: {enable_perspective_view}\nenable-flat-view: {enable_flat_view}\nenable-free-flight-view: {enable_free_flight_view}\nenable-hires: {enable_hires}\nstorage: "{storage}"\nignore-missing-light-data: {ignore_missing_light_data}\nmarker-sets: {{}}\n'),
        ),
        migrations.RunPython(update_existing_map_templates, migrations.RunPython.noop),
    ]
