# Generated by Django 5.2.16 on 2026-07-19 00:39

from django.db import migrations, models


def use_render_config_placeholders(apps, schema_editor):
    BlueMapProfile = apps.get_model("bluemap_configs", "BlueMapProfile")
    replacements = {
        "start-pos: {{ x: 0, z: 0 }}": "start-pos: {start_pos}",
        "start-pos: { x: 0, z: 0 }": "start-pos: {start_pos}",
        "render-mask: []": "render-mask: {render_mask}",
        "marker-sets: {{}}": "marker-sets: {marker_sets}",
        "marker-sets: {}": "marker-sets: {marker_sets}",
    }
    for profile in BlueMapProfile.objects.all():
        config_template = profile.config_template
        updated_template = config_template
        for old, new in replacements.items():
            updated_template = updated_template.replace(old, new)
        if updated_template != config_template:
            profile.config_template = updated_template
            profile.save(update_fields=["config_template"])


def restore_static_render_config_values(apps, schema_editor):
    BlueMapProfile = apps.get_model("bluemap_configs", "BlueMapProfile")
    replacements = {
        "start-pos: {start_pos}": "start-pos: {{ x: 0, z: 0 }}",
        "render-mask: {render_mask}": "render-mask: []",
        "marker-sets: {marker_sets}": "marker-sets: {{}}",
    }
    for profile in BlueMapProfile.objects.all():
        config_template = profile.config_template
        updated_template = config_template
        for old, new in replacements.items():
            updated_template = updated_template.replace(old, new)
        if updated_template != config_template:
            profile.config_template = updated_template
            profile.save(update_fields=["config_template"])


class Migration(migrations.Migration):

    dependencies = [
        ('bluemap_configs', '0010_alter_bluemapprofile_config_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluemapprofile',
            name='config_template',
            field=models.TextField(default='world: "{world_path}"\ndimension: "{dimension}"\nname: "{display_name}"\nsorting: {sorting}\nstart-pos: {start_pos}\nsky-color: "{sky_color}"\nvoid-color: "{void_color}"\nsky-light: {sky_light}\nambient-light: {ambient_light}\nremove-caves-below-y: {remove_caves_below_y}\ncave-detection-ocean-floor: {cave_detection_ocean_floor}\ncave-detection-uses-block-light: {cave_detection_uses_block_light}\nmin-inhabited-time: {min_inhabited_time}\nrender-mask: {render_mask}\nrender-edges: {render_edges}\nedge-light-strength: {edge_light_strength}\nenable-perspective-view: {enable_perspective_view}\nenable-flat-view: {enable_flat_view}\nenable-free-flight-view: {enable_free_flight_view}\nenable-hires: {enable_hires}\nstorage: "{storage}"\nignore-missing-light-data: {ignore_missing_light_data}\nmarker-sets: {marker_sets}\n'),
        ),
        migrations.RunPython(use_render_config_placeholders, restore_static_render_config_values),
    ]
