# Generated by Django 5.2 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bluemap_configs", "0011_alter_bluemapprofile_config_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="bluemapprofile",
            name="marker_command_template",
            field=models.CharField(
                default='"{bluemap_cli}" -c "{config_dir}" --markers',
                max_length=500,
            ),
        ),
    ]
