# Generated by Django 5.2.16 on 2026-07-16 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('cron_expression', models.CharField(blank=True, max_length=120)),
                ('interval_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('retry_failures', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('render', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='projects.render')),
            ],
            options={
                'ordering': ['render__atlas__project__name', 'name'],
            },
        ),
    ]
