# Generated by Django 5.2.16 on 2026-07-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="renderjob",
            name="operation",
            field=models.CharField(
                choices=[("update", "Update"), ("rebuild", "Rebuild")],
                default="update",
                max_length=20,
            ),
        ),
    ]
