# Generated by Django 5.2 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renders", "0002_renderjob_operation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="renderjob",
            name="operation",
            field=models.CharField(
                choices=[
                    ("update", "Update"),
                    ("rebuild", "Rebuild"),
                    ("markers", "Publish markers"),
                ],
                default="update",
                max_length=20,
            ),
        ),
    ]
